### ISSUE TITLE
2.1.30 unexpected behaviour

### ISSUE THREAD

**Issue by robertklep** [athombv/node-athom-cli#100]
It doesn't seem to transfer `node_modules/` (have not yet dug deeper, will update if I find out more).

2.1.24 (the previous version I had installed) worked just fine.

**EDIT**: I think it's related to [this change](https://github.com/athombv/node-athom-cli/commit/fdf74ac0d5136424a970ef56bf34e7166dced423#diff-fade80ab9ee854b017bc9cddff7f03eaR317).

The app that failed didn't declare all dependencies in `package.json`.

**Comment by WeeJeWel** [comment]
Fixed (at least added logging)

**Comment by robertklep** [comment]
It looks like it's not handling scoped packages properly:

```
✓ Packing Homey App...
 — Skipping /node_modules/@xmpp
...
$ grep @xmpp package.json
"@xmpp/client": "^0.3.0",
```

**Comment by WeeJeWel** [comment]
I've reverted the changes and will think very hard about a better way to solve this.

**Comment by robertklep** [comment]
Quick and dirty:
```
const { execSync } = require('child_process');
const exclude = JSON.parse( execSync('npm prune --dry-run --json') ).removed.map(r => r.path);
```
