### ISSUE TITLE
Fallback to showing URL doesn't work on (headless) Linux

### ISSUE THREAD

**Issue by robertklep** [athombv/node-athom-cli#112]
[`opn(url)`](https://github.com/athombv/node-athom-cli/blob/24c952df87d571cbb352fe95011147190b2e4894/lib/AthomApi/index.js#L87) doesn't seem to do a whole lot on (headless?) Linux, it just stalls until the [timeout handler](https://github.com/athombv/node-athom-cli/blob/24c952df87d571cbb352fe95011147190b2e4894/lib/AthomApi/index.js#L106) gets called. So the backup URL is never shown either, just this:

```
✓ Logging in...
? Paste the code:
Timeout getting authorization code!
```

(as an aside: when the timeout is reached, the process isn't exiting).

**Comment by WeeJeWel** [comment]
Fixed
