### ISSUE TITLE
Support running/installing apps directly from Github

### ISSUE THREAD

**Issue by robertklep** [athombv/node-athom-cli#119]
For example:
```
$ athom app run robertklep/nl.nefit.easy
$ athom app install robertklep/nl.nefit.easy
$ athom app install robertklep/nl.nefit.easy#my-branch
```

I'd be happy to take a look at how to implement this.

**Comment by WeeJeWel** [comment]
Interacting with git is not within the scope of this project. It would also make it too easy for (non-developer) users to install a malicious app.
