### ISSUE TITLE
can not install app through cli

### ISSUE THREAD

**Issue by satbopper** [athombv/node-athom-cli#121]
Allthough homey is online and cli is updated i can login,select homey after the install command
but it refuses all the time with homey is offline
Solution ?????

**Comment by robertklep** [comment]
Could possibly be a Windows issue, there are other Windows users with the same problem ([ref](https://community.athom.com/t/install-app-s-via-cli/8231)).

**Comment by patrickdend** [comment]
My mac did the trick, the Windows computer didn't work.

**Comment by satbopper** [comment]
i used a win10 machine,all the time homey offline
then i have a virtual machine running from oracle with linux mint,so i installed the enviroment under mint
and voila homey offline

**Comment by zsetefan** [comment]
I had the same issue on windows 10. Reinstall npm i -g athom-cli did the trick for me...…..

**Comment by satbopper** [comment]
ok thanks for the message but it is solved
the reason was i could not reach internally homey (ping was not possible)
solution reset router and working again

**Comment by phgmhendrix** [comment]
Same problem. I have two Homeys, one at work and one at home. I currently only use Windows computers.
- When I try to install an app from work on my home-Homey it does NOT work.
- When I try to install an app from work on my work-Homey it does work.
- When I try to install an app from home on my home-Homey it does work.
- When I try to install an app from home on my work-Homey it does NOT work.

It is a network-thing I gues.
