### ISSUE TITLE
App icon.svg not showed

### ISSUE THREAD

**Issue by Maxmudjon** [athombv/node-athom-cli#122]
I can not add icons to applications 
![photo_2019-02-16_21-58-16](https://user-images.githubusercontent.com/23142922/52902685-011fe100-3236-11e9-8969-cd161a74a932.jpg)

this icon

[icon.zip](https://github.com/athombv/node-athom-cli/files/2872177/icon.zip)

**Comment by WeeJeWel** [comment]
Try again with this icon.


[icon.svg.zip](https://github.com/athombv/node-athom-cli/files/2874996/icon.svg.zip)
