### ISSUE TITLE
Error "Filepath does not exist: README.md" on "athom run app" 

### ISSUE THREAD

**Issue by cgHome** [athombv/node-athom-cli#124]
I have the problem that I can't test my new app anymore. 
When I start the app (athom app run) I get the following error message:  Filepath does not exist: README.md !

macOS / 10.14.3 & Alpine (Docker)
Athom-Cli: v2.1.81

Log:

athom app run
✓ Pre-processing app...
✓ Validating app...
✓ Homey App validated successfully against level `debug`
✓ Packing Homey App...
— App size: 1.39 MB
✓ Installing Homey App on `cFlat-Hub` (http://192.168.xx.xx:80)...
x Filepath does not exist: README.md

ls
CODE_OF_CONDUCT.md	README.tmp.md		default.json		package-lock.json
CONTRIBUTING.md		app.js			docs			package.json
LICENSE			app.json		locales			sarah.log
README.md		assets			node_modules		settings

**Comment by robertklep** [comment]
The problem is caused by `.homeyignore` containing `*.md`.

Apparently, validation of the app doesn't take `.homeyignore` into account, but installing the app does, so it validates correctly but fails when installing.

**Comment by WeeJeWel** [comment]
Thanks @robertklep
