### ISSUE TITLE
Help, Error "str.replace is not a function"

### ISSUE THREAD

**Issue by kentaclub** [athombv/node-athom-cli#125]
hi Athom, I need help on my CLI, I tried removing the Athom-CLI and Nodejs, and reinstalling.
![str](https://user-images.githubusercontent.com/42129672/56265975-3f8e2b00-6115-11e9-992d-2e934574c573.jpg)
Node : v8.9.4
Athom-cli : 2.1.83

**Comment by WeeJeWel** [comment]
I cannot reproduce this issue. What's your Athom User ID? You can find this in the URL at https://accounts.athom.com when logged in.

**Comment by WeeJeWel** [comment]
Closed due to inactivity.
