### ISSUE TITLE
"homey offline" when running app from manager account

### ISSUE THREAD

**Issue by Adyku** [athombv/node-athom-cli#129]
When trying to install an app using a manager account, we receive the error "Homey Offline":
Homey App validated successfully against level `debug`
Homey Offline

**Comment by WeeJeWel** [comment]
This happens when your PC cannot connect to Homey. Usually this error occurs when you're not on the same Wi-Fi (LAN) network.

You can also try to connect Homey over USB. On Windows, you need to change the mode here: https://developer.athom.com/tools/settings

**Comment by Adyku** [comment]
Well, using the Owner account I am able to upload and work on my Homey from anywhere (not restricted by Wi-Fi). This is not possible using the Manager account. Why?
