### ISSUE TITLE
/api/manager/devkit/log/ returns 404

### ISSUE THREAD

**Issue by matjaz** [athombv/node-athom-cli#13]
https://github.com/athombv/node-athom-cli/blob/e4819859499294163a51f396a5b78efb54b96702/lib/project.js#L269

https://github.com/athombv/homey/issues/438#issuecomment-207947289

**Comment by WeeJeWel** [comment]
Does this happen on Homeys where a session is created?

**Comment by matjaz** [comment]
no. aha so this is just for devmode? no problem then.

**Comment by WeeJeWel** [comment]
Yep :)
