### ISSUE TITLE
athom app driver create doesnt check whether the current folder is an app

### ISSUE THREAD

**Issue by tjallingt** [athombv/node-athom-cli#134]
## steps to reproduce

in any folder run:

```sh
mkdir test
cd test
athom app driver create
```

and complete the driver creation wizard.

## expected behaviour

Get an error that the folder is not an athom/homey app (there is no valid `app.json`).

## actual behaviour

Command succeeds and creates a drivers folder in the current directory.

**Comment by KyleAthom** [comment]
This has been fixed in the major CLI update.
