### ISSUE TITLE
option     athom project --run appdir doesnt work in windows

### ISSUE THREAD

**Issue by nattlip** [athombv/node-athom-cli#14]
adding the appdir option to point at it , doesnt work in windows.

**Comment by WeeJeWel** [comment]
What command are you executing? This works for me:

```
C:\Users\emile\Git>athom project --run C:\Users\emile\Git\nl.athom.hello
```

**Comment by nattlip** [comment]
i do this , because here is my node.j prompt

C:\Program Files\nodejs athom project --run C:\Users\Jilles\Documents\visual studio 2015\Projects\homey 433\homey 433\pietje.homey.433

**Comment by bvdbos** [comment]
Guessing: There's a space in the path so you'll probably have to enclose it in double-quotes?

**Comment by bvdbos** [comment]
just tested:
`PS C:\> athom project --install C:\homey\nos strip`
doesn't work but
`PS C:\> athom project --install "C:\homey\nos strip"`
does

**Comment by nattlip** [comment]
yes it does,  so the help could be changed in athom -- run  ["path"]

**Comment by matjaz** [comment]
This is general knowledge parameter values should be quoted if includes spaces. actually it makes sense.

**Comment by nattlip** [comment]
Just as in real language:

"This is general knowledge, parameter values should be quoted if includes spaces. Actually it makes sense."
