### ISSUE TITLE
add method to clean node_modules

### ISSUE THREAD

**Issue by WeeJeWel** [athombv/node-athom-cli#15]
Remove:
- `tests`
- `examples`
- images in subfolders

**Comment by matjaz** [comment]
images are not that simple. at least keep ones in assets.

**Comment by WeeJeWel** [comment]
https://github.com/pingyhq/nm-prune

**Comment by matjaz** [comment]
https://github.com/tj/node-prune

**Comment by KyleAthom** [comment]
@RobinBol has integrated this functionality in the new version.
