### ISSUE TITLE
Publish requires README.txt while README.md is required for processing

### ISSUE THREAD

**Issue by fiLLLip** [athombv/node-athom-cli#153]
CLI says
![image](https://user-images.githubusercontent.com/1264369/71772484-c311d580-2f4b-11ea-97db-f06dd1bae429.png)

then I rename to .txt and publish, and web portal says
![image](https://user-images.githubusercontent.com/1264369/71772483-bbeac780-2f4b-11ea-9976-e3c498927ef3.png)

https://github.com/athombv/node-athom-cli/blob/4373f676de5408325f64b67a5d7a599c4ccedc64/lib/App/index.js#L311

**Comment by Thorarin** [comment]
I've also experienced this. It seems like an issue with the server side processing, so so much the CLI itself.

**Comment by fiLLLip** [comment]
The documentation around this (and much else in homey) is super lacking (imo), but I found the reason why the cli requires a txt, and its because you need a clear text version for the app store. My publishing was rejected because I had markdown in my file. It would be helpful for the cli to explain why it needs a txt file.

**Comment by RobinBol** [comment]
Hi! Currently, apps require both a README.md and a README.txt. The explanation is that older Homey firmware requires the .md file, while the new app store requires a .txt file. You are right that documentation is lacking, we are working on improving the documentation in general. I will add this specific item to docs, thank you for reporting.

**Comment by WeeJeWel** [comment]
We've made a change in the App Store so this error never appears anymore. You're now free to remove the README.md as you like.
