### ISSUE TITLE
Debugging not working on windows

### ISSUE THREAD

**Issue by Sillyjan** [athombv/node-athom-cli#23]
Trying to debug on Windows dos not open the debug connection to Homey (usb and network)
Nodejs version 4.6 (also tested on 4.5)
Also removed the virus scanner and disabled the firewall.
```
D:\test\com.athom.hello>athom project --run
? Select active Homey: Homey @ 192.168.1.165:80
1/4 - Archiving...
2/4 - Uploading to Homey @ 192.168.1.165:80...
3/4 - Running `com.athom.hello`, press CTRL+C to abort...
-------------------------------------------------
```

**Comment by SergeRegoor** [comment]
Together with Sillyjan we found this bug. We encountered the probleem on my laptop first (Windows 10 Pro 64-bit), then on Sillyjan's Windows laptop as well. The debug log worked fine on Sillyjan's Mac, though.
We tried re-installing the athom-cli, too.

**Comment by magtimmermans** [comment]
Same issue

**Comment by nlrb** [comment]
Same issue here after upgrading to 0.10.5. Doing a new 'npm install -g athom-cli' fixed it.

**Comment by nattlip** [comment]
@nlrb , me to

**Comment by magtimmermans** [comment]
Me to :)

**Comment by SergeRegoor** [comment]
After updating to 0.10.5, debugging worked again. Still kept working after updating the cli as well.

**Comment by WeeJeWel** [comment]
Fixed it :-) It was an updated dependency. So run `npm uninstall -g athom-cli; npm install -g athom-cli` to fix it.

**Comment by gruijter** [comment]
HELP! I just upgraded CLI, and now my console hangs on step 3 when doing athom project --run

![2016-10-14](https://cloud.githubusercontent.com/assets/19174120/19391689/faba4a58-922d-11e6-9e13-7762f4f18b19.png)

**Comment by magtimmermans** [comment]
Make sure homey is upgraded and remove homey-cli and reinstall it

**Comment by gruijter** [comment]
With help og @WeeJeWel it was solved by doing this (for Windows):
```
go to `%AppData%\npm\node_modules\athom-cli`
delete 'node_modules/socket.io-client' 
run `npm install socket.io-client@1.5.0`
```

**Comment by gruijter** [comment]
for OSX the path is: /usr/local/lib/node or /usr/local/lib/node_modules

**Comment by MarvinSchenkel** [comment]
Same issue here. @gruijter workaround is not working unfortunately. Any suggestions? Homey is definitely on the latest version (0.10.5) and I did a reinstall of athom-cli. Then tried @gruiter s workaround, but no luck!

**Comment by nattlip** [comment]
[https://github.com/athombv/node-athom-cli/issues/24#issuecomment-253996156](url)
