### ISSUE TITLE
athom-cli 1.0.32 doesn't work for me.

### ISSUE THREAD

**Issue by nattlip** [athombv/node-athom-cli#24]
windows 7 64bit 1.0.31 worked fine.    i get stuck at line 3/4 after downloading , mentioned earlier in version 1.0.30 by some people, therfore version 1.0.31  and now 1.0.32 . nlrb also do'wngraded to 1.0.31 after instlling 1.0.32 see developers slack

**Comment by bvdbos** [comment]
Some more information would be usefull. What doesn't work? Doesn't it even start?

**Comment by nattlip** [comment]
comment updated

**Comment by nattlip** [comment]
i downgraded to 1.0.31  $ npm install -g athom-cli@1.0.31

**Comment by DieterKoblenz** [comment]
Same problem here using 1.0.32 no debugging info.

**Comment by nattlip** [comment]
in 0.10.7 this issue reappeared with athom-cli 1.0.31

**Comment by nattlip** [comment]
athom cli 1.0.31 works with firmware 0.10.7 on windows
