### ISSUE TITLE
Kaku APA3-1500R does not work in flows

### ISSUE THREAD

**Issue by TheMrCaveman** [athombv/node-athom-cli#30]
Kaku apa3-1500r socket does not work in flows.
When you test the flow it works perfectly!

When a flow is activated it shows the device as activated but nothing happened.

**Comment by bvdbos** [comment]
Should be filed under:
https://github.com/athombv/homey/issues
This repo is for the CLI. Also could you try setting a delay of 2 seconds?
https://github.com/athombv/homey/issues/1041
so please close this one and if the issue is different file a new one on the correct place...

**Comment by TheMrCaveman** [comment]
Okay i closed this issue it works with a delay!
