### ISSUE TITLE
Athom 2.0.3 beta [Windows] Ctrl-C also asks to terminate batch job

### ISSUE THREAD

**Issue by Dijker** [athombv/node-athom-cli#40]
When I terminate an app on homey started with Athom app run with a Ctrl-C 

✓ Installing Homey App on `BerliozHomeyR&D` (http://10.1.13.202:80)...
✓ Homey App `nu.dijker.papertrails` successfully installed
✓ Running `nu.dijker.papertrails`, press CTRL+C to quit
─────────────── Logging stdout/stderr ───────────────
--- INFO: nu.dijker.papertrails has been killed ---
✓ Uninstalling `nu.dijker.papertrails`...
✓ Homey App `nu.dijker.papertrails` successfully uninstalled
Terminate batch job (Y/N)? n

(so probably disable Break ;-) )

**Comment by WeeJeWel** [comment]
Fixed, thanks for reporting!

**Comment by Dijker** [comment]
Confirmed works !!! Thanks!
