### ISSUE TITLE
Thrown error doesnt tell me where to look. 

### ISSUE THREAD

**Issue by mruiter** [athombv/node-athom-cli#46]
Errors like this doesnt tell me anything about where to look in a app that has 16 drivers in it.
A little more details or a echo of the line involved in this error would give some real help and not confusion.

**Comment by mruiter** [comment]
[
    {
        "keyword": "enum",
        "dataPath": ".drivers[0].settings[0].type",
        "schemaPath": "#/items/oneOf/0/properties/type/enum",
        "params": {
            "allowedValues": [
                "text",
                "password",
                "textarea",
                "label"
            ]
        },
        "message": "should be equal to one of the allowed values"
    },
    {
        "keyword": "type",
        "dataPath": ".drivers[0].settings[0].id",
        "schemaPath": "#/items/oneOf/1/properties/id/type",
        "params": {
            "type": "string"
        },
        "message": "should be string"
    },
    {
        "keyword": "enum",
        "dataPath": ".drivers[0].settings[0].type",
        "schemaPath": "#/items/oneOf/2/properties/type/enum",
        "params": {
            "allowedValues": [
                "radio",
                "dropdown"
            ]
        },
        "message": "should be equal to one of the allowed values"
    },
    {
        "keyword": "enum",
        "dataPath": ".drivers[0].settings[0].type",
        "schemaPath": "#/items/oneOf/3/properties/type/enum",
        "params": {
            "allowedValues": [
                "checkbox"
            ]
        },
        "message": "should be equal to one of the allowed values"
    },
    {
        "keyword": "enum",
        "dataPath": ".drivers[0].settings[0].type",
        "schemaPath": "#/items/oneOf/4/properties/type/enum",
        "params": {
            "allowedValues": [
                "group"
            ]
        },
        "message": "should be equal to one of the allowed values"
    },
    {
        "keyword": "oneOf",
        "dataPath": ".drivers[0].settings[0]",
        "schemaPath": "#/items/oneOf",
        "params": {
            "passingSchemas": null
        },
        "message": "should match exactly one schema in oneOf"
    }

**Comment by WeeJeWel** [comment]
The path is specified: `drivers[0].settings[0].type`

So the first driver, first setting, property `type`
