### ISSUE TITLE
Declare minimal Node.js requirement

### ISSUE THREAD

**Issue by robertklep** [athombv/node-athom-cli#47]
Because [`fs.copyFile`](https://github.com/athombv/node-athom-cli/blob/bf8242253d5bed86864f79cb8eaa99b80f04437a/lib/App/index.js#L23) is being used, there's an implicit minimal Node.js requirement of v8.5.0.

It's advisable to explicitly declare this in `package.json`:
```
"engines": {
  "node": ">=8.5.0"
}
```

Otherwise, people running older versions of Node.js will run into uncaught exceptions because `fs.copyFile` is undefined.

**Comment by WeeJeWel** [comment]
Thank you
