### ISSUE TITLE
Composer crashes on unexpected .js file in drivers dir

### ISSUE THREAD

**Issue by RobinBol** [athombv/node-athom-cli#67]
```
ENOTDIR: not a directory, open '/Users/robinbolscher/Development/apps/com.qubino/drivers/genericDevice.js/driver.compose.json'

Aborting.
```

**Comment by RobinBol** [comment]
Well, having a `GenericDriver.js` class from which the other drivers in the `/driver_id` dir extend makes sense (to me at least) to place in the driver dir.

**Comment by WeeJeWel** [comment]
Personally I prefer to put this in `/lib`

**Comment by WeeJeWel** [comment]
I've thought about this, and I still think that the `/drivers/` folder should contain only folders for real drivers. Any helpers should be moved to `/lib/` or a similar location.
