### ISSUE TITLE
Update version of `homey-lib` dependency

### ISSUE THREAD

**Issue by robertklep** [athombv/node-athom-cli#86]
Currently (looking at `athom-cli@2.1.20`) there's a dependency on `homey-lib@^2.2.1`, which may cause issues when updating `athom-cli` to newer versions.

For instance, `homey-lib@2.2.6` fixes a validation issue ([here](https://github.com/athombv/node-homey-lib/blob/d0b146181c423c90bc481a010dba976e118776f7/lib/App/index.js#L193)), but because of the outdated dependency, it may not get installed when someone installs `athom-cli`.

As a (probably) related issue, some apps fail validation when being submitted to the app store, while local validation passes.

**Comment by WeeJeWel** [comment]
Thank you! We have fixed this issue and both the appstore and athom-cli are built automatically after a homey-lib change.
