### ISSUE TITLE
v2.1.22 validation error - schema is invalid: data.definitions['zwaveDevice']....

### ISSUE THREAD

**Issue by PeterEIER** [athombv/node-athom-cli#90]
After updating to latest version of the CLI v2.1.22 have this error when installing my app which before validated without any problem.

✓ Validating app...
✘ Homey App did not validate against level `debug`:
schema is invalid: data.definitions['zwaveDevice'].properties['associationGroupsOptions'].properties['type'] should be object,boolean
Not installing, please fix the validation issues first

---

**Comment by WeeJeWel** [comment]
Oops, sorry for the inconvenience! It should be fixed if you `npm i -g athom-cli`.
